#!/usr/bin/env bash
# print "Best School" 10 times using while loop and if condition

declare -i idx=0
while (( idx < 10 ))
do
    echo "Best School"
    if (( idx == 8 ))
	then
	echo "Hi"
	fi
    (( idx++ ))
done
